### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by duonox** [gothinkster/angularjs-realworld-example-app#19]
when use gulp I got the below  error

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\Sávio Oliveira\Downloads\Compressed\angularjs-realworld-example-app-master\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Sávio Oliveira\Downloads\Compressed\angularjs-realworld-example-app-master\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Sávio Oliveira\Downloads\Compressed\angularjs-realworld-example-app-master\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)

gulp -v
CLI version: 2.2.0
Local version: 3.9.0

how can i fix the error

**Comment by Thomas-Machielsen** [comment]
Hi, I encountered the same error today.
Googling pointed me to this SO thread: https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

Downgrading Node to version 8 made it work for me. 
(Version 8 was a hunch, I'm not sure which highest version works, maybe 10 might work as well, I'd stay with even versions, since those are stable Node versions)
