### ISSUE TITLE
Lock version to Angular 1.5

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/angularjs-realworld-example-app#6]
Angular 1.6 is breaking UI-Router, so I'm thinking we'll just lock this in at 1.5 for the time being.

**Comment by MickelSierra85** [comment]
Hi,

Even with Angular 1.5.0.rc2 I get:

```
Error: transition superseded
    at $StateProvider.$get (http://localhost:4000/main.js:2904:42)
    at Object.invoke (http://localhost:4000/main.js:9403:19)
    at http://localhost:4000/main.js:9197:37
    at getService (http://localhost:4000/main.js:9344:32)
    at injectionArgs (http://localhost:4000/main.js:9369:58)
    at Object.invoke (http://localhost:4000/main.js:9395:18)
    at http://localhost:4000/main.js:12506:43
    at forEach (http://localhost:4000/main.js:4898:20)
    at Object.<anonymous> (http://localhost:4000/main.js:12504:13)
    at Object.invoke (http://localhost:4000/main.js:9403:19) Possibly unhandled rejection: {}
(anonymous) @ main.js:18903
(anonymous) @ main.js:15400
processChecks @ main.js:21256
$eval @ main.js:22558
$digest @ main.js:22368
$apply @ main.js:22666
bootstrapApply @ main.js:6386
invoke @ main.js:9403
doBootstrap @ main.js:6384
bootstrap @ main.js:6404
4../article @ main.js:37738
s @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
main.js:18903 Error: transition prevented
    at $StateProvider.$get (http://localhost:4000/main.js:2905:41)
    at Object.invoke (http://localhost:4000/main.js:9403:19)
    at http://localhost:4000/main.js:9197:37
    at getService (http://localhost:4000/main.js:9344:32)
    at injectionArgs (http://localhost:4000/main.js:9369:58)
    at Object.invoke (http://localhost:4000/main.js:9395:18)
    at http://localhost:4000/main.js:12506:43
    at forEach (http://localhost:4000/main.js:4898:20)
    at Object.<anonymous> (http://localhost:4000/main.js:12504:13)
    at Object.invoke (http://localhost:4000/main.js:9403:19) Possibly unhandled rejection: {}
(anonymous) @ main.js:18903
(anonymous) @ main.js:15400
processChecks @ main.js:21256
$eval @ main.js:22558
$digest @ main.js:22368
$apply @ main.js:22666
bootstrapApply @ main.js:6386
invoke @ main.js:9403
doBootstrap @ main.js:6384
bootstrap @ main.js:6404
4../article @ main.js:37738
s @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
main.js:18903 Error: transition aborted
    at $StateProvider.$get (http://localhost:4000/main.js:2906:39)
    at Object.invoke (http://localhost:4000/main.js:9403:19)
    at http://localhost:4000/main.js:9197:37
    at getService (http://localhost:4000/main.js:9344:32)
    at injectionArgs (http://localhost:4000/main.js:9369:58)
    at Object.invoke (http://localhost:4000/main.js:9395:18)
    at http://localhost:4000/main.js:12506:43
    at forEach (http://localhost:4000/main.js:4898:20)
    at Object.<anonymous> (http://localhost:4000/main.js:12504:13)
    at Object.invoke (http://localhost:4000/main.js:9403:19) Possibly unhandled rejection: {}
(anonymous) @ main.js:18903
(anonymous) @ main.js:15400
processChecks @ main.js:21256
$eval @ main.js:22558
$digest @ main.js:22368
$apply @ main.js:22666
bootstrapApply @ main.js:6386
invoke @ main.js:9403
doBootstrap @ main.js:6384
bootstrap @ main.js:6404
4../article @ main.js:37738
s @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
main.js:18903 Error: transition failed
    at $StateProvider.$get (http://localhost:4000/main.js:2907:38)
    at Object.invoke (http://localhost:4000/main.js:9403:19)
    at http://localhost:4000/main.js:9197:37
    at getService (http://localhost:4000/main.js:9344:32)
    at injectionArgs (http://localhost:4000/main.js:9369:58)
    at Object.invoke (http://localhost:4000/main.js:9395:18)
    at http://localhost:4000/main.js:12506:43
    at forEach (http://localhost:4000/main.js:4898:20)
    at Object.<anonymous> (http://localhost:4000/main.js:12504:13)
    at Object.invoke (http://localhost:4000/main.js:9403:19) Possibly unhandled rejection: {}
(anonymous) @ main.js:18903
(anonymous) @ main.js:15400
processChecks @ main.js:21256
$eval @ main.js:22558
$digest @ main.js:22368
$apply @ main.js:22666
bootstrapApply @ main.js:6386
invoke @ main.js:9403
doBootstrap @ main.js:6384
bootstrap @ main.js:6404
4../article @ main.js:37738
s @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
```

**Comment by enricator** [comment]
@MickelSierra85 Same here, but I resolved the issue updating the dependency for UI-router

Change the reference in your _package.json_:
```
[...]
"dependencies": {
    "angular": "^1.5.0-rc.2",
    "angular-ui-router": "^0.3.2",
[...]
```

and re-run 
`npm install`

**Comment by EricSimons** [comment]
https://github.com/gothinkster/angularjs-realworld-example-app/pull/11
